export const NAVIGATE_TO = "NAVIGATE_TO";
export const NAVIGATE_TO_UP_ONE_LEVEL = "NAVIGATE_TO_UP_ONE_LEVEL";
export const NAVIGATE_TO_HOME = "NAVIGATE_TO_HOME";
export const NAVIGATE_TO_BACK = "NAVIGATE_TO_BACK";
export const NAVIGATE_TO_FORWARD = "NAVIGATE_TO_FORWARD";
export const FORCE_RELOAD = "FORCE_RELOAD";
