export const UPDATE_FILE_SEARCH_KEYWORDS = "UPDATE_FILE_SEARCH_KEYWORDS";
export const UPDATE_USER_SEARCH_KEYWORDS = "UPDATE_USER_SEARCH_KEYWORDS";
export const SET_USER_SEARCH_RESULT_LIST = " SET_USER_SEARCH_RESULT_LIST";
