export const REQUEST_FORGOT_PASSWORD = "REQUEST_FORGOT_PASSWORD";
export const REQUEST_RESET_PASSWORD = "REQUEST_RESET_PASSWORD";
export const REQUEST_LOGIN = "REQUEST_LOGIN";

export const SAVE_USER = "SAVE_USER";
export const REMOVE_USER = "REMOVE_USER";
export const ADD_DRIVE = "ADD_DRIVE";
export const ADD_TAG = "ADD_TAG";

export const FETCH_DRIVE_ACCOUNTS_LIST = "FETCH_DRIVE_ACCOUNTS_LIST";
export const FETCH_TAGS_LIST = "FETCH_TAGS_LIST";
export const REMOVE_ALL_GOOGLE_DRIVE_ACCOUNTS =
  "REMOVE_ALL_GOOGLE_DRIVE_ACCOUNTS";
export const REMOVE_GOOGLE_DRIVE_ACCOUNT_BY_EMAIL =
  "REMOVE_GOOGLE_DRIVE_ACCOUNT_BY_EMAIL";
